### ISSUE TITLE
Your password is plaintext in this project

### ISSUE THREAD

**Issue by daj** [HariSoni87/Repo#1]
Presumably this is not deliberate?
https://github.com/HariSoni87/Repo/blob/7c4012184f21a48f239550ca2691a3d177d506f9/Edition/gradle.properties

**Comment by HariSoni87** [comment]
Removed thanks a lot..

**Comment by daj** [comment]
I recommend you delete the whole history of this file, since the link above still contains the sensitive information.

Here's advice on how to do it:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Another option is to just delete the repository and recreate it.
